### ISSUE TITLE
Allow for reuse of Skippable classes for custom test runner purposes

### ISSUE THREAD

**Issue by DavidRMaltby** [AArnott/Xunit.SkippableFact#17]
I'm working on a custom tool which is used for product support to take health checks on their products.  Its logic makes use of the ability to inherit xUnit classes and override certain methods to extend functionality.  I was wondering if you'd be open to a PR to do the same for SkippableFact library.  For a few specific instances of what is blocking me:
- The SkippableFactTestCase class that is nested in the SkippableFactDiscoverer class is internal.  
- The SkippableFactDiscoverer.Discover() which creates the instance of SkippableFactTestCase does not have the "virtual" keyword.

It would be unfortunate, if my tool needed to use a forked version of some of the SkippableFact library by copying source for full classes, when it could just inherit, override certain methods and call "base.<method>()" to preserve this library's functionality even as it evolves in the future.

Thank you for your time and I'd be happy to promptly submit the trivial PR, if this is something that you'd consider.

**Comment by AArnott** [comment]
Sure. I'll take that PR.

**Comment by AArnott** [comment]
Closed by #18
