### ISSUE TITLE
SkippableFact and FXCop code analysis rule CA1822: Mark members as static

### ISSUE THREAD

**Issue by Atrejoe** [AArnott/Xunit.SkippableFact#23]
SkippableFact are often marked as "Should be static" by code rule: CA1822

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822

As (X)unit tests should be non-static, allowing test setup and teardown in class constructors and destructors, I think this check should not apply.
Is there anything this library can do, or should this be taken up with the [Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers) maintainers?

I guess that if they check for attributes that can be *assigned to* `FactAttribute` instead of strictly the `FactAttribute`, it would be fine, as [SkippableFactAttribute](https://github.com/AArnott/Xunit.SkippableFact/blob/master/src/Xunit.SkippableFact/SkippableFactAttribute.cs) inherits from [FactAttribute](https://github.com/xunit/xunit/blob/main/src/xunit.v3.core/FactAttribute.cs).

I don't see a blanket rule that I could apply to all skippable tests here:
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-quality-rule-options

How do you see this? Have you tackled this before too?

**Comment by AArnott** [comment]
I haven't noticed this myself. But AFAIK there's nothing *this* repo can do. Please file an issue against the analyzer: https://github.com/dotnet/roslyn-analyzers
