### ISSUE TITLE
Global fallback for missing calls to Skip.If()

### ISSUE THREAD

**Issue by thomaseyde** [AArnott/Xunit.SkippableFact#27]
Would it be possible to create a global fallback for missing calls to `Skip.If(...)`?

**Comment by AArnott** [comment]
What is a 'global fallback'?

**Comment by thomaseyde** [comment]
Some kind of a default action set in config file or global state.

**Comment by AArnott** [comment]
I'm afraid I'm still not understanding. Can you provide an example? 

From the test extension's perspective, we have 0 insight into whether the test method may or may not execute a `Skip.If()` call before the test method is executed. And if the test method executes and `Skip` is never called, we can't tell that either. And even if we could tell, it's perfectly valid for a branch in the test to have skipped the call to `Skip.If`. What would this 'default action' do anyway?

**Comment by thomaseyde** [comment]
I would like the default behavior to be skipped. I can see that this is
technically not possible, because you have to run something. But if a call
to `Skip.If` was never called, then the test could fail with a message
explaining what was forgotten.

**Comment by AArnott** [comment]
Sorry. That would be a significant breaking change, and force a bunch of users' tests to put in a stub `Skip.If` call just to get their tests working again, that were already appropriately skipping but using other mechanisms.
