### ISSUE TITLE
SkippableFact is not recognized in dnx46 but works in coreclr

### ISSUE THREAD

**Issue by IlyaBiryukov** [AArnott/Xunit.SkippableFact#3]
Hi,

We have a test project with [SkippableFact] on some tests. These tests are not executed on dnx46 but run fine on dnxcore50.

dnvm use 1.0.0-rc2-16351 -r coreclr
dnx -p test/UnitTests test
... UnitTests  Total: 62

dnvm use 1.0.0-rc2-16351 -r clr
dnx -p test/UnitTests test
... UnitTests  Total: 58

All our skippable tests have this Skip.IfNot(), but they're not executed (I've verified by setting a break point on a line above it and it doesn't hit):

Skip.IfNot(RuntimeInformation.IsOSPlatform(OSPlatform.Windows), "Fails on *nix");

We use "Xunit.SkippableFact": "1.2.14"

**Comment by bragma** [comment]
Same problem here using Net Core 1.0.1
Is there any way to make it work?
Thanks!

**Comment by fubar-coder** [comment]
Same problem here

**Comment by MattBigYellowDesign** [comment]
Same problem on DNX451

**Comment by AArnott** [comment]
DNX isn't a supported platform by MSFT any more, so Won't Fixing.
