### ISSUE TITLE
Currently does not support .Net Core

### ISSUE THREAD

**Issue by fuglyducky** [AArnott/Xunit.SkippableFact#4]
This project is exactly what I have been looking for. Are there any plans to support .Net Core?

**Comment by 304NotModified** [comment]
I see [1.3.1](https://www.nuget.org/packages/Xunit.SkippableFact/1.3.1) supports .Net Standard 1.1. and so I think this is solved!

**Comment by NickCraver** [comment]
@AArnott Can close this out :)
