### ISSUE TITLE
Nuget package doesn't seem to get the updates from main

### ISSUE THREAD

**Issue by paule96** [AArnott/Xunit.SkippableFact#40]
I see here on github still updates happens in the repository but since 2020 their is no new release on nuget? Are their any reason why that should be like that?

**Comment by AArnott** [comment]
sure. There haven't been any feature updates or fixes since 2020.
The updates to the repo that you see are just chores to keep dependencies updated and pipelines building.

**Comment by paule96** [comment]
@AArnott thanks for the clarification
