### ISSUE TITLE
Doesn't seem to work on a UWP test project

### ISSUE THREAD

**Issue by thnk2wn** [AArnott/Xunit.SkippableFact#5]
In a UWP app, a unit test marked with [SkippableTest] results in Test Explorer not being able to discover it and therefore never run it / evaluate the skip condition.

Running all the tests I do see a warning in the output:
Test adapter sent back a result for an unknown test case. Ignoring result for 'MyTestNameHere'.

**Comment by AArnott** [comment]
It looks to me like if this used to fail, it works in VS 2017, so I'd chalk this up to a bug in the test discovery system of VS. You can see in the screenshot below, even before I built for the first time, that the skippable test is discovered.

![image](https://user-images.githubusercontent.com/3548/40596411-63e4a0b8-61ef-11e8-8c03-3f5f7ab0f65a.png)
